<style type="text/css">
    .scrollable2 {
        position:relative;
        overflow:hidden;
        height: 800px;
        width: 800px;
        background-color: white;
    }

    .scrollable2 .items2 {
        position:absolute;
        height:20000em;
    }
    .vertical2 {  
        position:relative;
        overflow:hidden;	
        height: 600px;	 
        width: 800px;
        margin-top: -5px;
        border-radius: 20px;
        background-color: rgb(0,153,0);
    }

    .items2 {	
        position:absolute;
        height:20000em;	
        margin: 0px;

    }


    .item2 {
        /*        border-top:5px solid rgb(0,102,51);*/
        border-right: 5px dotted rgb(0,102,51);
        margin:10px 0;
        padding:15px;
        font-size:12px;
        height:700;
        overflow: hidden;

    }


    .item2 img {
        float:left;
        margin-right:20px;
        margin-top: 60px;
        height:180px;
        width:240px;
    }

    .item2 h3 {
        margin:0px 0px 50px -20px;
        font-size:35px;
        color: white;
        font-weight:normal;
        text-align: center;
        width: 100%;
        font-weight: bold;
    }

    .item2 p
    {
        text-align: justify;
        font-size: 23px;
        color: white;

    }


    #actions2 {
        width:700px;
        margin:30px 0 10px 0;	
    }

    #actions2 a {
        font-size:23px;		
        cursor:pointer;
        color:#666;
    }

    #actions2 a:hover {
        text-decoration:underline;
        color:#000;
    }

    .disabled2 {
        visibility:hidden;		
    }

    .next2 {
        float:right;
    }	

    .prev2
    {
        margin-left: 100px;
        float: left;
    }

    div.judul2 h2
    {
        float: left;
        color: rgb(215,215,62);
        margin: 5px 0px 0px 20px;
        font-size: 30px;
        text-shadow: 2px 4px 5px black;

    }


</style>

<hr style="border: 3px solid rgb(0,102,51); width: 772px;margin-left: 20px">
<br/>

<div class="scrollable2 vertical2">


    <div class="items2">
        <!--list-->
        <div>

            <div class="item2">

                <h3>ronaldo </h3>
                <br/><br/><br/><br/><br/>
                <img src="<?php echo base_url(); ?>image/Barcelona_128.png"/>
                <p>
                    <a href="#">Read more</a> 
                </p>

                <p>
                    zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
                    Ronaldo Luís NazárRonaldo Luís Nazário de LRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (RonRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís NazáriRonaldo Luís NazárRonaldo Luís Nazário de LRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaRonaldo Luís NazárRonaldo Luís Nazário de LRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (RonRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciatioalRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (PortuguesRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciatioe pronunciatiodo Luís NazárRonaldo LuíldoRonaldo Luís NazárRonaldo Luís Nazário de LRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (RonRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciatioalRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (PortuguesRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo LuazárRonaRonaldo Luís NazárRonaldo Luís Nazário de LRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (RonRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciatioalRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (PortuguesRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciatioe pronunciatiodo Luís NazárRonaldo LuíldoRonaldo Luís NazárRonaldo Luís Nazário de LRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (RonRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciatioalRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (PortuguesRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciatioe pronunciatiodo Luís NazárRonaldo Luí Luís Nazário dRonaldo Luís NazárRonaldo Luís Nazário de LRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldoazárRonaRonaldo Luís NazárRonaldo Luís Nazário de LRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (RonRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciatioalRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (PortuguesRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciatioe pronunciatiodo Luís NazárRonaldo LuíldoRonaldo Luís NazárRonaldo Luís Nazário de LRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (RonRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciatioalRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (PortuguesRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciatioe pronunciatiodo Luís NazárRonaldo Luí Luís Nazário dRonaldo Luís NazárRonaldo Luís Nazário de LRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (RonRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldRonaldo Luís NazárRonaldo Luís Nazário de LRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (RonRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciatioalRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portugues Luís Nazário de Lima (RonRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldRonaldo Luís NazárRonaldo Luís Nazário de LRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (RonRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciatioalRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguesís Nazário de Lima (Portuguese pronunciatioe pronunciatiodo Luís NazárRonaldo Luí Luís Nazário dRonaldo Luís NazárRonaldo Luís Nazário de LRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (RonRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldRonaldo Luís NazárRonaldo Luís Nazário de LRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (RonRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciatioalRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (PortuguesRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciatioe pronunciatiodo Luís NazárRonaldo Luío Luís Nazário de Lima (Portuguese pronunciatioalRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (PortuguesRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciatioe pronunciatiodo Luís NazárRonaldo Luíe Lima (RonRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciatioalRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (PortuguesRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciatioe pronunciatiodo Luís NazárRonaldo Luío de Lima (Portuguese pronunciatioalRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (PortuguesRonaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciatioe pronunciatiodo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciatioPortuguese pronunciatioima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário d

                </p>



            </div>

        </div> <!--end list-->

        <div>

            <div class="item2">

                <h3>title</h3>

                <img src="<?php echo base_url(); ?>image/Icon001.png"/>


                <p>
                    <a href="#">Read more</a> 
                </p>

                <p>
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário d

                </p>

                <p>
                    <a href="#">Read more</a> 
                </p>

            </div>

        </div> <!--end list-->

        <div>

            <div class="item2">


                <h3>title</h3>
                <img src="<?php echo base_url(); ?>image/Icon001.png"/>

                <p>
                    <a href="#">Read more</a> 
                </p>
                <p>
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário d

                </p>

                <p>
                    <a href="#">Read more</a>
                </p>

            </div>

        </div> <!--end list-->


        <div>

            <div class="item2">

                <h3>title</h3>
                <img src="<?php echo base_url(); ?>image/Icon001.png"/>
                <p>
                    <a href="#">Read more</a> 
                </p>
                <p>
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 SeLima (PoRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Sertuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 September 1976[1]), commonly known as Ronaldo, is a retired Brazilian footballer who last played for Corinthians. Ronaldo is widely considered to be the greatest 'pure' striker in the history of the modern game, and by some accounts, in the history of football. Ronaldo was one of the most prolific scorers in the world in the late 1990s and the early 2000s. He won his first Ballon d'Or as the European Footballer of the Year in 1997 (aged only 21) and again won the award in 2002 (26 years old). Additionally, he is one of only two men to have won the FIFA Player of the Year award three times, along with French footballer Zinedine Zidane.
                    Ronaldo Luís NazárRonaldo Luís Nazário de Lima (Portuguese pronunciation: [χoˈnawdu luˈiz naˈzaɾiu dʒi ˈlimɐ]; born 18 Seio de Ronaldo Luís Nazário d

                </p>

                <p>
                    <a href="#">Read more</a>
                </p>

            </div>

        </div> <!--end list-->



    </div>

</div>

<script>

    $(function() {			
        $(".scrollable2").scrollable({ vertical: true, mousewheel: true });		
    });
</script>





